2025-02-26 01:05:37,142 INFO [MainThread]: Starting archive loader with configuration:
2025-02-26 01:05:37,143 INFO [MainThread]:   num_workers: 8
2025-02-26 01:05:37,145 INFO [MainThread]:   queue_size: 32
2025-02-26 01:05:37,147 INFO [MainThread]:   batch_size: 25000
2025-02-26 01:05:37,148 INFO [MainThread]:   retention_days: 7000
2025-02-26 01:05:37,150 INFO [MainThread]:   log_level: DEBUG
2025-02-26 01:05:37,151 INFO [MainThread]:   changeset_file: /archives/changesets.osm.bz2
2025-02-26 01:05:37,153 INFO [MainThread]:   buffer_size: 524288
2025-02-26 01:05:37,155 INFO [MainThread]:   start_sequence: 5999999
2025-02-26 01:05:37,156 INFO [Producer]: Producer started. Cutoff date: 2005-12-28T01:05:37.156216+00:00
2025-02-26 01:05:37,159 INFO [Producer]: Reading from file: /archives/changesets.osm.bz2
2025-02-26 01:05:37,184 INFO [Consumer-1]: Consumer started.
2025-02-26 01:05:37,191 INFO [Consumer-2]: Consumer started.
2025-02-26 01:05:37,200 INFO [Consumer-3]: Consumer started.
2025-02-26 01:05:37,209 INFO [Consumer-4]: Consumer started.
2025-02-26 01:05:37,215 INFO [Consumer-5]: Consumer started.
2025-02-26 01:05:37,222 INFO [Consumer-6]: Consumer started.
2025-02-26 01:05:37,227 INFO [Consumer-7]: Consumer started.
2025-02-26 01:05:37,234 INFO [Consumer-8]: Consumer started.
2025-02-26 01:05:37,384 INFO [Producer]: Processed 10000 changesets... (Queued: 8692, Skipped: 1308)
2025-02-26 01:05:37,594 INFO [Producer]: Processed 20000 changesets... (Queued: 18692, Skipped: 1308)
2025-02-26 01:05:37,789 DEBUG [Consumer-1]: Inserting batch with first changeset: {'id': 1309, 'username': 'rsopp', 'uid': 1222, 'created_at': datetime.datetime(2005, 12, 28, 0, 3, 20, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2005, 12, 28, 4, 44, 43, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 461, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((6.9843545 50.8913862, 6.9843545 50.958667, 6.883893 50.958667, 6.883893 50.8913862, 6.9843545 50.8913862))'}
2025-02-26 01:05:37,841 ERROR [Consumer-1]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:37,845 INFO [Consumer-1]: Inserted/updated 25000 changesets.
2025-02-26 01:05:37,894 INFO [Producer]: Processed 30000 changesets... (Queued: 28692, Skipped: 1308)
2025-02-26 01:05:38,100 INFO [Producer]: Processed 40000 changesets... (Queued: 38692, Skipped: 1308)
2025-02-26 01:05:38,324 INFO [Producer]: Processed 50000 changesets... (Queued: 48692, Skipped: 1308)
2025-02-26 01:05:38,391 DEBUG [Consumer-2]: Inserting batch with first changeset: {'id': 26309, 'username': 'sorein', 'uid': 25906, 'created_at': datetime.datetime(2009, 4, 1, 22, 15, 46, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2009, 4, 1, 23, 45, 25, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 9, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((26.7159738 47.4693998, 26.7159738 47.503667, 26.6972279 47.503667, 26.6972279 47.4693998, 26.7159738 47.4693998))'}
2025-02-26 01:05:38,440 ERROR [Consumer-2]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:38,443 INFO [Consumer-2]: Inserted/updated 25000 changesets.
2025-02-26 01:05:38,609 INFO [Producer]: Processed 60000 changesets... (Queued: 58692, Skipped: 1308)
2025-02-26 01:05:38,813 INFO [Producer]: Processed 70000 changesets... (Queued: 68692, Skipped: 1308)
2025-02-26 01:05:39,013 DEBUG [Consumer-3]: Inserting batch with first changeset: {'id': 51309, 'username': 'dk42', 'uid': 15220, 'created_at': datetime.datetime(2009, 2, 2, 11, 42, 54, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2009, 2, 2, 12, 45, 27, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 105, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((37.5973366 55.5733394, 37.5973366 55.5760147, 37.5942475 55.5760147, 37.5942475 55.5733394, 37.5973366 55.5733394))'}
2025-02-26 01:05:39,065 ERROR [Consumer-3]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:39,067 INFO [Consumer-3]: Inserted/updated 25000 changesets.
2025-02-26 01:05:39,134 INFO [Producer]: Processed 80000 changesets... (Queued: 78692, Skipped: 1308)
2025-02-26 01:05:39,343 INFO [Producer]: Processed 90000 changesets... (Queued: 88692, Skipped: 1308)
2025-02-26 01:05:39,540 INFO [Producer]: Processed 100000 changesets... (Queued: 98692, Skipped: 1308)
2025-02-26 01:05:39,597 DEBUG [Consumer-4]: Inserting batch with first changeset: {'id': 76309, 'username': 'MartinDornfelder', 'uid': 14029, 'created_at': datetime.datetime(2008, 8, 5, 14, 20, 44, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2008, 8, 5, 15, 28, 48, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 8, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((14.3308497 51.7278691, 14.3308497 51.7352108, 14.3246179 51.7352108, 14.3246179 51.7278691, 14.3308497 51.7278691))'}
2025-02-26 01:05:39,645 ERROR [Consumer-4]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:39,654 INFO [Consumer-4]: Inserted/updated 25000 changesets.
2025-02-26 01:05:39,879 INFO [Producer]: Processed 110000 changesets... (Queued: 108692, Skipped: 1308)
2025-02-26 01:05:40,097 INFO [Producer]: Processed 120000 changesets... (Queued: 118692, Skipped: 1308)
2025-02-26 01:05:40,258 DEBUG [Consumer-5]: Inserting batch with first changeset: {'id': 101309, 'username': 'user_5121', 'uid': 5121, 'created_at': datetime.datetime(2007, 6, 18, 19, 51, 2, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2007, 6, 18, 21, 17, 24, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 547, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((-0.0269832 51.8709407, -0.0269832 51.9395375, -0.1670135 51.9395375, -0.1670135 51.8709407, -0.0269832 51.8709407))'}
2025-02-26 01:05:40,304 ERROR [Consumer-5]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:40,307 INFO [Consumer-5]: Inserted/updated 25000 changesets.
2025-02-26 01:05:40,367 INFO [Producer]: Processed 130000 changesets... (Queued: 128692, Skipped: 1308)
2025-02-26 01:05:40,581 INFO [Producer]: Processed 140000 changesets... (Queued: 138692, Skipped: 1308)
2025-02-26 01:05:40,847 INFO [Producer]: Processed 150000 changesets... (Queued: 148692, Skipped: 1308)
2025-02-26 01:05:40,906 DEBUG [Consumer-6]: Inserting batch with first changeset: {'id': 126309, 'username': 'Firman Hadi', 'uid': 76518, 'created_at': datetime.datetime(2008, 12, 5, 11, 50, 56, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2008, 12, 5, 13, 0, 49, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 488, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((106.9994974 -6.2577965, 106.9994974 -6.1211186, 106.9262409 -6.1211186, 106.9262409 -6.2577965, 106.9994974 -6.2577965))'}
2025-02-26 01:05:40,956 ERROR [Consumer-6]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:40,959 INFO [Consumer-6]: Inserted/updated 25000 changesets.
2025-02-26 01:05:41,132 INFO [Producer]: Processed 160000 changesets... (Queued: 158692, Skipped: 1308)
2025-02-26 01:05:41,341 INFO [Producer]: Processed 170000 changesets... (Queued: 168692, Skipped: 1308)
2025-02-26 01:05:41,511 DEBUG [Consumer-7]: Inserting batch with first changeset: {'id': 151309, 'username': 'M E Menk', 'uid': 1694, 'created_at': datetime.datetime(2007, 7, 17, 18, 40, 52, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2007, 7, 18, 0, 30, 25, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 1698, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((5.479833 59.4848387, 5.479833 61.406312, 4.565941 61.406312, 4.565941 59.4848387, 5.479833 59.4848387))'}
2025-02-26 01:05:41,559 ERROR [Consumer-7]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:41,562 INFO [Consumer-7]: Inserted/updated 25000 changesets.
2025-02-26 01:05:41,625 INFO [Producer]: Processed 180000 changesets... (Queued: 178692, Skipped: 1308)
2025-02-26 01:05:41,906 INFO [Producer]: Processed 190000 changesets... (Queued: 188692, Skipped: 1308)
2025-02-26 01:05:42,113 INFO [Producer]: Processed 200000 changesets... (Queued: 198692, Skipped: 1308)
2025-02-26 01:05:42,179 DEBUG [Consumer-8]: Inserting batch with first changeset: {'id': 176309, 'username': 'CVI', 'uid': 34088, 'created_at': datetime.datetime(2008, 4, 17, 19, 59, 27, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2008, 4, 17, 20, 59, 58, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 2, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POINT (0 0)'}
2025-02-26 01:05:42,225 ERROR [Consumer-8]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:42,228 INFO [Consumer-8]: Inserted/updated 25000 changesets.
2025-02-26 01:05:42,399 INFO [Producer]: Processed 210000 changesets... (Queued: 208692, Skipped: 1308)
2025-02-26 01:05:42,618 INFO [Producer]: Processed 220000 changesets... (Queued: 218692, Skipped: 1308)
2025-02-26 01:05:42,789 DEBUG [Consumer-1]: Inserting batch with first changeset: {'id': 201309, 'username': 'mos6510', 'uid': 10466, 'created_at': datetime.datetime(2007, 8, 10, 11, 47, 5, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2007, 8, 10, 14, 6, 40, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 34, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((149.2284151 -35.3499854, 149.2284151 -35.343187, 149.2102269 -35.343187, 149.2102269 -35.3499854, 149.2284151 -35.3499854))'}
2025-02-26 01:05:42,834 ERROR [Consumer-1]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:42,837 INFO [Consumer-1]: Inserted/updated 25000 changesets.
2025-02-26 01:05:42,906 INFO [Producer]: Processed 230000 changesets... (Queued: 228692, Skipped: 1308)
2025-02-26 01:05:43,167 INFO [Producer]: Processed 240000 changesets... (Queued: 238692, Skipped: 1308)
2025-02-26 01:05:43,384 INFO [Producer]: Processed 250000 changesets... (Queued: 248692, Skipped: 1308)
2025-02-26 01:05:43,450 DEBUG [Consumer-2]: Inserting batch with first changeset: {'id': 226309, 'username': None, 'uid': 0, 'created_at': datetime.datetime(2007, 2, 28, 10, 3, 39, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2007, 2, 28, 11, 29, 15, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 14, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((10.8897935 59.2029304, 10.8897935 59.2104174, 10.8791987 59.2104174, 10.8791987 59.2029304, 10.8897935 59.2029304))'}
2025-02-26 01:05:43,493 ERROR [Consumer-2]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:43,496 INFO [Consumer-2]: Inserted/updated 25000 changesets.
2025-02-26 01:05:43,665 INFO [Producer]: Processed 260000 changesets... (Queued: 258692, Skipped: 1308)
2025-02-26 01:05:43,878 INFO [Producer]: Processed 270000 changesets... (Queued: 268692, Skipped: 1308)
2025-02-26 01:05:44,057 DEBUG [Consumer-3]: Inserting batch with first changeset: {'id': 251309, 'username': 'ThomasKlosa', 'uid': 5065, 'created_at': datetime.datetime(2007, 3, 30, 23, 24, 6, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2007, 3, 31, 0, 25, 21, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 64, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((13.6905128 51.0410408, 13.6905128 51.062961, 13.6422788 51.062961, 13.6422788 51.0410408, 13.6905128 51.0410408))'}
2025-02-26 01:05:44,101 ERROR [Consumer-3]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:44,105 INFO [Consumer-3]: Inserted/updated 25000 changesets.
2025-02-26 01:05:44,155 INFO [Producer]: Processed 280000 changesets... (Queued: 278692, Skipped: 1308)
2025-02-26 01:05:44,366 INFO [Producer]: Processed 290000 changesets... (Queued: 288692, Skipped: 1308)
2025-02-26 01:05:44,587 INFO [Producer]: Processed 300000 changesets... (Queued: 298692, Skipped: 1308)
2025-02-26 01:05:44,710 DEBUG [Consumer-4]: Inserting batch with first changeset: {'id': 276309, 'username': 'gisle', 'uid': 8313, 'created_at': datetime.datetime(2007, 10, 21, 14, 58, 56, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2007, 10, 21, 16, 45, 31, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 54, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((5.3637383 60.330355, 5.3637383 60.3435718, 5.35142 60.3435718, 5.35142 60.330355, 5.3637383 60.330355))'}
2025-02-26 01:05:44,755 ERROR [Consumer-4]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:44,757 INFO [Consumer-4]: Inserted/updated 25000 changesets.
2025-02-26 01:05:44,932 INFO [Producer]: Processed 310000 changesets... (Queued: 308692, Skipped: 1308)
2025-02-26 01:05:45,140 INFO [Producer]: Processed 320000 changesets... (Queued: 318692, Skipped: 1308)
2025-02-26 01:05:45,307 DEBUG [Consumer-5]: Inserting batch with first changeset: {'id': 301309, 'username': 'mawi42', 'uid': 42393, 'created_at': datetime.datetime(2008, 10, 13, 13, 42, 10, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2008, 10, 13, 14, 45, 55, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 48, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((11.6938039 47.8506031, 11.6938039 47.8699443, 11.6827311 47.8699443, 11.6827311 47.8506031, 11.6938039 47.8506031))'}
2025-02-26 01:05:45,350 ERROR [Consumer-5]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:45,353 INFO [Consumer-5]: Inserted/updated 25000 changesets.
2025-02-26 01:05:45,423 INFO [Producer]: Processed 330000 changesets... (Queued: 328692, Skipped: 1308)
2025-02-26 01:05:45,635 INFO [Producer]: Processed 340000 changesets... (Queued: 338692, Skipped: 1308)
2025-02-26 01:05:45,842 INFO [Producer]: Processed 350000 changesets... (Queued: 348692, Skipped: 1308)
2025-02-26 01:05:45,902 DEBUG [Consumer-6]: Inserting batch with first changeset: {'id': 326309, 'username': 'NicRoets', 'uid': 1186, 'created_at': datetime.datetime(2007, 10, 27, 10, 49, 9, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2007, 10, 27, 13, 45, 1, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 372, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((18.2390324 -26.5793956, 18.2390324 -21.7512393, 13.9522784 -21.7512393, 13.9522784 -26.5793956, 18.2390324 -26.5793956))'}
2025-02-26 01:05:45,946 ERROR [Consumer-6]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:45,948 INFO [Consumer-6]: Inserted/updated 25000 changesets.
2025-02-26 01:05:46,121 INFO [Producer]: Processed 360000 changesets... (Queued: 358692, Skipped: 1308)
2025-02-26 01:05:46,392 INFO [Producer]: Processed 370000 changesets... (Queued: 368692, Skipped: 1308)
2025-02-26 01:05:46,557 DEBUG [Consumer-7]: Inserting batch with first changeset: {'id': 351309, 'username': 'Nielsen 72', 'uid': 25501, 'created_at': datetime.datetime(2008, 3, 19, 9, 27, 35, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2008, 3, 19, 10, 27, 35, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 1, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POINT (10.2090249 56.1364322)'}
2025-02-26 01:05:46,602 ERROR [Consumer-7]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:46,604 INFO [Consumer-7]: Inserted/updated 25000 changesets.
2025-02-26 01:05:46,669 INFO [Producer]: Processed 380000 changesets... (Queued: 378692, Skipped: 1308)
2025-02-26 01:05:46,881 INFO [Producer]: Processed 390000 changesets... (Queued: 388692, Skipped: 1308)
2025-02-26 01:05:47,099 INFO [Producer]: Processed 400000 changesets... (Queued: 398692, Skipped: 1308)
2025-02-26 01:05:47,156 DEBUG [Consumer-8]: Inserting batch with first changeset: {'id': 376309, 'username': 'Pihlaja', 'uid': 11386, 'created_at': datetime.datetime(2008, 12, 14, 18, 8, 31, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2008, 12, 14, 19, 13, 37, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 488, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((27.4557186 64.113478, 27.4557186 64.2334391, 27.2418764 64.2334391, 27.2418764 64.113478, 27.4557186 64.113478))'}
2025-02-26 01:05:47,202 ERROR [Consumer-8]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:47,205 INFO [Consumer-8]: Inserted/updated 25000 changesets.
2025-02-26 01:05:47,379 INFO [Producer]: Processed 410000 changesets... (Queued: 408692, Skipped: 1308)
2025-02-26 01:05:47,580 INFO [Producer]: Processed 420000 changesets... (Queued: 418692, Skipped: 1308)
2025-02-26 01:05:47,748 DEBUG [Consumer-1]: Inserting batch with first changeset: {'id': 401309, 'username': 'minusgrader', 'uid': 31103, 'created_at': datetime.datetime(2009, 2, 13, 9, 13, 55, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2009, 2, 13, 10, 14, 16, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 86, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((9.3554898 48.6091147, 9.3554898 48.6182643, 9.3449807 48.6182643, 9.3449807 48.6091147, 9.3554898 48.6091147))'}
2025-02-26 01:05:47,860 ERROR [Consumer-1]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:47,863 INFO [Consumer-1]: Inserted/updated 25000 changesets.
2025-02-26 01:05:47,932 INFO [Producer]: Processed 430000 changesets... (Queued: 428692, Skipped: 1308)
2025-02-26 01:05:48,147 INFO [Producer]: Processed 440000 changesets... (Queued: 438692, Skipped: 1308)
2025-02-26 01:05:48,362 INFO [Producer]: Processed 450000 changesets... (Queued: 448692, Skipped: 1308)
2025-02-26 01:05:48,414 DEBUG [Consumer-2]: Inserting batch with first changeset: {'id': 426309, 'username': 'fbsoft', 'uid': 57963, 'created_at': datetime.datetime(2008, 10, 18, 20, 24, 58, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2008, 10, 18, 22, 10, 35, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 94, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((6.9548364 52.5174613, 6.9548364 52.5814636, 6.8422944 52.5814636, 6.8422944 52.5174613, 6.9548364 52.5174613))'}
2025-02-26 01:05:48,460 ERROR [Consumer-2]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:48,462 INFO [Consumer-2]: Inserted/updated 25000 changesets.
2025-02-26 01:05:48,629 INFO [Producer]: Processed 460000 changesets... (Queued: 458692, Skipped: 1308)
2025-02-26 01:05:48,841 INFO [Producer]: Processed 470000 changesets... (Queued: 468692, Skipped: 1308)
2025-02-26 01:05:49,009 DEBUG [Consumer-3]: Inserting batch with first changeset: {'id': 451309, 'username': 'Ehmi', 'uid': 30186, 'created_at': datetime.datetime(2008, 7, 10, 7, 16, 57, tzinfo=datetime.timezone.utc), 'closed_at': datetime.datetime(2008, 7, 10, 8, 33, 38, tzinfo=datetime.timezone.utc), 'open': False, 'num_changes': 34, 'comments_count': 0, 'tags': {}, 'comments': [], 'bbox': 'POLYGON ((10.6601062 51.2550827, 10.6601062 51.2712161, 10.6255708 51.2712161, 10.6255708 51.2550827, 10.6601062 51.2550827))'}
2025-02-26 01:05:49,054 ERROR [Consumer-3]: Batch insert failed: tuple index out of range
Traceback (most recent call last):
  File "/app/osm_meet_your_mappers/db_utils.py", line 77, in upsert_changesets
    execute_values(
  File "/usr/local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2025-02-26 01:05:49,057 INFO [Consumer-3]: Inserted/updated 25000 changesets.
2025-02-26 01:05:49,126 INFO [Producer]: Processed 480000 changesets... (Queued: 478692, Skipped: 1308)
2025-02-26 01:05:49,407 INFO [Producer]: Processed 490000 changesets... (Queued: 488692, Skipped: 1308)
2025-02-26 01:05:49,603 INFO [Producer]: Processed 500000 changesets... (Queued: 498692, Skipped: 1308)
